version: "3.8"

services:
  db:
    image: postgres:16
    container_name: postgres_catalogo
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: catalogo
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis
    container_name: redis_catalogo
    ports:
      - "6379:6379"

volumes:
  postgres_data:
