spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/catalogo
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: catalogo-api
  docker:
    compose:
      enabled: true
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
